"""Fail-closed validation for SQL generated by the Bedrock agent."""

MAX_QUERY_LENGTH = 10_000

# These tokens are never needed for the sample's read-only question-answering flow.
# String literal contents are excluded from tokenization before this set is checked.
FORBIDDEN_KEYWORDS = frozenset(
    {
        "ALTER",
        "ANALYZE",
        "CALL",
        "COMMENT",
        "COMMIT",
        "CREATE",
        "DEALLOCATE",
        "DELETE",
        "DESCRIBE",
        "DROP",
        "EXECUTE",
        "EXPLAIN",
        "EXTERNAL",
        "FUNCTION",
        "GRANT",
        "INFORMATION_SCHEMA",
        "INSERT",
        "INTO",
        "JSON_TABLE",
        "LATERAL",
        "MATCH_RECOGNIZE",
        "MERGE",
        "MSCK",
        "OPTIMIZE",
        "PREPARE",
        "PROCEDURE",
        "QUERY",
        "REFRESH",
        "RESET",
        "REVOKE",
        "ROLLBACK",
        "SET",
        "SHOW",
        "START",
        "SYSTEM",
        "TABLE",
        "TABLESAMPLE",
        "TRUNCATE",
        "UNLOAD",
        "UNNEST",
        "UPDATE",
        "USE",
        "VACUUM",
        "WITH",
    }
)


class QueryValidationError(ValueError):
    """Raised when agent-generated SQL is outside the supported safe subset."""


def _read_string_literal(query, start):
    """Return the first index after an Athena single-quoted string literal."""
    index = start + 1
    while index < len(query):
        if query[index] != "'":
            index += 1
            continue
        if index + 1 < len(query) and query[index + 1] == "'":
            index += 2
            continue
        return index + 1
    raise QueryValidationError("The SQL query contains an unterminated string literal.")


def _scan_query(query):
    """Collect unquoted tokens and statement delimiters while rejecting ambiguity."""
    tokens = []
    semicolons = []
    parenthesis_depth = 0
    index = 0

    while index < len(query):
        character = query[index]
        next_character = query[index + 1] if index + 1 < len(query) else ""

        if character == "'":
            index = _read_string_literal(query, index)
            continue

        if character in {'"', "`"}:
            raise QueryValidationError(
                "Quoted identifiers are not supported by this sample."
            )

        if (character == "-" and next_character == "-") or (
            character == "/" and next_character == "*"
        ):
            raise QueryValidationError("SQL comments are not supported by this sample.")

        if character in {"#", "$", "\\"}:
            raise QueryValidationError("The SQL query contains an unsupported character.")

        if character == ";":
            semicolons.append(index)
            index += 1
            continue

        if character == "(":
            parenthesis_depth += 1
            index += 1
            continue

        if character == ")":
            parenthesis_depth -= 1
            if parenthesis_depth < 0:
                raise QueryValidationError("The SQL query has unbalanced parentheses.")
            index += 1
            continue

        if ord(character) > 127:
            raise QueryValidationError(
                "Only ASCII SQL syntax is supported by this sample."
            )

        if character.isdigit():
            end = index + 1
            while end < len(query) and (
                query[end].isascii()
                and (query[end].isalnum() or query[end] == "_")
            ):
                end += 1
            numeric_token = query[index:end]
            if any(
                token_character.isalpha() or token_character == "_"
                for token_character in numeric_token
            ):
                raise QueryValidationError(
                    "Numeric literals cannot contain letters or underscores."
                )
            index = end
            continue

        if character.isalpha() or character == "_":
            end = index + 1
            while end < len(query):
                token_character = query[end]
                if not token_character.isascii() or not (
                    token_character.isalnum() or token_character == "_"
                ):
                    break
                end += 1
            tokens.append(query[index:end].upper())
            index = end
            continue

        if ord(character) < 32 and character not in {"\t", "\n", "\r"}:
            raise QueryValidationError("The SQL query contains a control character.")

        index += 1

    if parenthesis_depth:
        raise QueryValidationError("The SQL query has unbalanced parentheses.")

    return tokens, semicolons


def validate_read_only_query(query):
    """Validate and normalize one agent-generated, read-only Athena SELECT query."""
    if not isinstance(query, str):
        raise QueryValidationError("The SQL query must be a string.")

    normalized_query = query.strip()
    if not normalized_query:
        raise QueryValidationError("The SQL query cannot be empty.")
    if len(normalized_query) > MAX_QUERY_LENGTH:
        raise QueryValidationError(
            f"The SQL query exceeds the {MAX_QUERY_LENGTH}-character limit."
        )

    tokens, semicolons = _scan_query(normalized_query)
    if semicolons:
        delimiter = semicolons[0]
        if len(semicolons) != 1 or normalized_query[delimiter + 1 :].strip():
            raise QueryValidationError("Only one SQL statement is allowed.")
        normalized_query = normalized_query[:delimiter].rstrip()

    if not tokens or tokens[0] != "SELECT":
        raise QueryValidationError("Only read-only SELECT statements are allowed.")

    forbidden_tokens = FORBIDDEN_KEYWORDS.intersection(tokens)
    obfuscated_forbidden_tokens = {
        token
        for token in tokens
        if "".join(character for character in token if character.isalpha())
        in FORBIDDEN_KEYWORDS
    }
    if forbidden_tokens or obfuscated_forbidden_tokens:
        raise QueryValidationError("Only read-only SELECT statements are allowed.")

    return normalized_query
