export BEDROCK_AGENT_ID=U8TWVNTXPJ
export BEDROCK_AGENT_ALIAS_ID=TSTALIASID
export SESSION_ID=12345
export BEDROCK_KB_ID=9VFKA9OKIZ
export BEDROCK_DS_ID=U4YRTDTOCD
export KB_BUCKET_NAME=bedrock-bedrock-kb
export AWS_REGION=us-east-1