"""Provision an IAM gateway role + an AgentCore Gateway + an FMKB Retrieve target.

Writes resource ids to ../.env.fmkb-gateway so 02-strands-agent can pick them up.

Idempotency: re-running with the same --name-prefix reuses the existing gateway
role, gateway, and KB target by exact-name match — no orphans on re-run.
Names are deterministic (no random suffix) so reuse actually triggers.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time

import boto3
from botocore.exceptions import ClientError

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from utils.managed_kb import assert_kb_active  # noqa: E402
from utils import gateway as gw  # noqa: E402


def get_or_create_gateway_role(name: str, account_id: str, region: str,
                               kb_id: str) -> str:
    iam = boto3.client("iam")
    trust = json.dumps(gw.gateway_role_trust_policy(account_id, region))
    perms = json.dumps(
        gw.gateway_role_permission_policy(account_id, region, kb_id=kb_id)
    )
    try:
        iam.create_role(
            RoleName=name,
            AssumeRolePolicyDocument=trust,
            Description="AgentCore Gateway role for FMKB Retrieve",
        )
        print(f"created role {name}")
    except ClientError as e:
        if e.response["Error"]["Code"] != "EntityAlreadyExists":
            raise
        iam.update_assume_role_policy(RoleName=name, PolicyDocument=trust)
        print(f"role {name} exists; refreshed trust policy")
    iam.put_role_policy(
        RoleName=name, PolicyName=f"{name}-inline", PolicyDocument=perms,
    )
    role_arn = iam.get_role(RoleName=name)["Role"]["Arn"]
    # IAM is eventually consistent; AgentCore will reject the role if it tries to
    # assume it before it's visible. A short wait avoids "role not found" on first deploy.
    time.sleep(8)
    return role_arn


def get_or_create_gateway(name: str, role_arn: str, region: str) -> dict:
    control = boto3.client("bedrock-agentcore-control", region_name=region)
    for page in control.get_paginator("list_gateways").paginate():
        for it in page["items"]:
            if it["name"] == name and it["status"] == "READY":
                full = control.get_gateway(gatewayIdentifier=it["gatewayId"])
                print(f"reusing gateway {full['gatewayId']}")
                return full
    print(f"creating gateway {name}…")
    return gw.create_gateway(name=name, role_arn=role_arn, region=region)


def get_or_create_target(gateway_id: str, name: str, kb_id: str, region: str) -> dict:
    control = boto3.client("bedrock-agentcore-control", region_name=region)
    for it in control.list_gateway_targets(gatewayIdentifier=gateway_id).get("items", []):
        if it["name"] == name and it["status"] == "READY":
            print(f"reusing target {it['targetId']}")
            return control.get_gateway_target(
                gatewayIdentifier=gateway_id, targetId=it["targetId"]
            )
    print(f"creating target {name}…")
    return gw.create_kb_target(
        gateway_id=gateway_id, kb_id=kb_id, name=name, region=region,
    )


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--kb-id", required=True, help="Managed KB id (FMKB)")
    p.add_argument("--region", default="us-west-2")
    p.add_argument("--name-prefix", default="fmkb-sample",
                   help="prefix for the gateway role / gateway / target")
    args = p.parse_args()

    sts = boto3.client("sts").get_caller_identity()
    account_id = sts["Account"]
    print(f"caller={sts['Arn']}  account={account_id}  region={args.region}")

    assert_kb_active(args.kb_id, args.region)
    print(f"KB {args.kb_id} verified ACTIVE / MANAGED")

    # Deterministic names so a second run reuses the same gateway / target /
    # role instead of creating siblings and orphaning the originals.
    role_name = f"{args.name_prefix}-gateway-role"
    gw_name = f"{args.name_prefix}-gateway"
    target_name = f"{args.name_prefix}-target"

    role_arn = get_or_create_gateway_role(
        role_name, account_id, args.region, kb_id=args.kb_id,
    )
    gw_obj = get_or_create_gateway(gw_name, role_arn, args.region)
    target = get_or_create_target(gw_obj["gatewayId"], target_name, args.kb_id, args.region)

    env_path = ROOT / ".env.fmkb-gateway"
    env_path.write_text(
        "# auto-generated by 01-raw-mcp/setup_gateway.py\n"
        f"export REGION={args.region}\n"
        f"export ACCOUNT_ID={account_id}\n"
        f"export KB_ID={args.kb_id}\n"
        f"export GATEWAY_ID={gw_obj['gatewayId']}\n"
        f"export GATEWAY_URL={gw_obj['gatewayUrl']}\n"
        f"export TARGET_ID={target['targetId']}\n"
        f"export TARGET_NAME={target['name']}\n"
        f"export GATEWAY_ROLE_NAME={role_name}\n"
    )
    print(f"\nwrote {env_path}")
    print("source it:  source .env.fmkb-gateway")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
